dependencies:
- name: mysql
  version: "0.9.2"
  appVersion: 5.7.14
  repository: "@stable"
- name: redis
  repository: "@stable"
  version: "5.0"
- name: rabbitmq
  repository: "@stable"
  version: "3.6.3"
