{{- if .Values.persistence.nfs.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: monolith-volume-claim
spec:
  storageClassName: default-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
{{- end }}