{{- if .Values.global.persistence.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "monoloth.fullname" . }}-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.99.1
    path: {{.Values.global.monolith.volumeHostPath}}
{{- end }}
