apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-monolith
  labels:
    app: {{ include "monoloth.name" . }}
    app.kubernetes.io/name: {{ include "monoloth.name" . }}
    helm.sh/chart: {{ include "monoloth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.global.monolith.service.type }}
  ports:
    - port: {{ .Values.global.monolith.service.port }}
      nodePort: {{ .Values.global.monolith.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "monoloth.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: magento2-redis
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
